server {
    listen 8000;
    server_name localhost;

    client_max_body_size 20M;

    root /home/erra/projects/cloud27;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        include                 fastcgi.conf;
        fastcgi_pass            unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_param           SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_index           index.php;

        # VERY IMPORTANT — prevent PHP truncating uploads
        fastcgi_param   PHP_VALUE "upload_max_filesize=20M \n post_max_size=20M";
    }

    location /assets  { try_files $uri =404; }
    location /uploads { try_files $uri =404; }

    location ~ /\.ht {
        deny all;
    }
}
